### ISSUE TITLE
Openhab 3 w. ohj module installed - No IntelliSense in VS code within rules

### ISSUE THREAD

**Issue by LukasA83** [jpg0/ohj#31]
Hi,

maybe an easy question: I'm right now moving from nashorn to graal including rewritting my rules and helpers. I will use ohj module to reduce some of the migration efforts. 
To edit my scripts I'm using VS code. I noticed, that there is no IntelliSense when I'm editing my rules while there is when creating helpers. 

Any suggestion to get intellisense w. JSDOC working for rules? Here is my folder structure:
![grafik](https://user-images.githubusercontent.com/58861945/133894765-8320abbd-5afd-497c-b057-9c919ba612c1.png)

**Comment by jpg0** [comment]
Don't really know about this - it's just standard JS, and it has a .js extension?

**Comment by LukasA83** [comment]
I fixed it by creating a jsconfig.json in the "project" root folder to specify the node modules path.
